name: "Tag new version"
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  new-tag:
    uses: bactions/workflows/.github/workflows/tag-new-version.yml@main
    secrets:
      deploy_key: ${{ secrets.RELEASE_KEY }}
